name: SimplexNoise CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Moonbit to PATH
        run: echo "$HOME/.moon/bin" >> $GITHUB_PATH

      - name: Update MoonBit registry
        run: moon update

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1

      - name: Run tests with coverage
        run: moon test --enable-coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ZSeanYves/SimplexNoise
